FROM debian

RUN apt-get update -qqy && \
    apt-get install --no-install-recommends -qqy sudo git curl && \
    useradd -m -G sudo debian && \
    passwd -d debian

USER debian
WORKDIR /home/debian
