FROM debian

RUN apt-get update -qqy && \
    apt-get install --no-install-recommends -qqy curl fontconfig sudo && \
    useradd -m -G sudo debian && \
    passwd -d debian && \
    # curl: (77) error setting certificate file: /etc/ssl/certs/ca-certificates.crt
    rm -f /etc/ssl/certs/ca-bundle.crt && \
    apt-get reinstall -qqy ca-certificates && \
    update-ca-certificates

USER debian
WORKDIR /home/debian
